Trace 0:
  Transitions:
    'PyLong_FromLong() succeeds'
    'taking False path'
    'taking True path'
    'returning'
  Return value:
    repr(): PointerToRegion(gcctype='struct PyObject *', loc=gcc.Location(file='tests/cpychecker/refcounts/use_after_dealloc/input.c', line=30), region=RegionOnHeap('PyLongObject', gcc.Location(file='tests/cpychecker/refcounts/use_after_dealloc/input.c', line=30)))
    str(): (struct PyObject *)&RegionOnHeap('PyLongObject', gcc.Location(file='tests/cpychecker/refcounts/use_after_dealloc/input.c', line=30)) from tests/cpychecker/refcounts/use_after_dealloc/input.c:30
    r->ob_refcnt: RefcountValue(1)
    r->ob_type: PointerToRegion(gcctype='struct PyTypeObject *', loc=gcc.Location(file='tests/cpychecker/refcounts/use_after_dealloc/input.c', line=30), region=RegionForGlobal(gcc.VarDecl('PyLong_Type')))
  Exception:
    (struct PyObject *)0 from tests/cpychecker/refcounts/use_after_dealloc/input.c:28

Trace 1:
  Transitions:
    'PyLong_FromLong() succeeds'
    'taking False path'
    'taking False path'
    'calling tp_dealloc on PyLongObject allocated at tests/cpychecker/refcounts/use_after_dealloc/input.c:30'
  error: ReadFromDeallocatedMemory()
  error: reading from deallocated memory at tests/cpychecker/refcounts/use_after_dealloc/input.c:42: memory deallocated at tests/cpychecker/refcounts/use_after_dealloc/input.c:41
  PyLongObject allocated at tests/cpychecker/refcounts/use_after_dealloc/input.c:30:
    repr(): RegionOnHeap('PyLongObject', gcc.Location(file='tests/cpychecker/refcounts/use_after_dealloc/input.c', line=30))
    str(): PyLongObject allocated at tests/cpychecker/refcounts/use_after_dealloc/input.c:30
    r->ob_refcnt: None
    r->ob_type: None
  Exception:
    (struct PyObject *)0 from tests/cpychecker/refcounts/use_after_dealloc/input.c:28

Trace 2:
  Transitions:
    'PyLong_FromLong() fails'
    'taking True path'
    'returning'
  Return value:
    repr(): ConcreteValue(gcctype='struct PyObject *', loc=None, value=0L)
    str(): (struct PyObject *)0L
  Exception:
    RegionForGlobal(gcc.VarDecl('PyExc_MemoryError'))
