tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c: In function 'test':
tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:45:29: error: calling PyDict_SetItem with NULL (gcc.VarDecl('value')) as argument 3 at tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:45
tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:33:10: note: when PyDict_New() succeeds at:     dict = PyDict_New();
tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:34:8: note: taking False path at:     if (!dict) {
tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:38:9: note: reaching:     key = PyLong_FromLong(500);
tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:38:9: note: when PyLong_FromLong() succeeds at:     key = PyLong_FromLong(500);
tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:39:11: note: when PyLong_FromLong() fails at:     value = PyLong_FromLong(1000);
tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:45:29: error: calling PyDict_SetItem with NULL (gcc.VarDecl('key')) as argument 2 at tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:45
tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:33:10: note: when PyDict_New() succeeds at:     dict = PyDict_New();
tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:34:8: note: taking False path at:     if (!dict) {
tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:38:9: note: reaching:     key = PyLong_FromLong(500);
tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:38:9: note: when PyLong_FromLong() fails at:     key = PyLong_FromLong(500);
tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:39:11: note: when PyLong_FromLong() succeeds at:     value = PyLong_FromLong(1000);
tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:45:29: note: found 1 similar trace(s) to this
tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c:28:1: note: graphical error report for function 'test' written out to 'tests/cpychecker/refcounts/PyDict_SetItem/incorrect/input.c.test-refcount-errors.html'
