tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c: In function 'test':
tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:35:nn: warning: ob_refcnt of return value is 1 too low [enabled by default]
tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:35:nn: note: was expecting final ob_refcnt to be N + 1 (for some unknown N)
tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:35:nn: note: due to object being referenced by: return value
tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:35:nn: note: but final ob_refcnt is N + 0
tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:35:nn: note: borrowed reference returned by PyDict_GetItem() allocated at:     return PyDict_GetItem(some_dict, args);
tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:35:nn: note: when treating unknown struct PyObject * from tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:26 as non-NULL at:     return PyDict_GetItem(some_dict, args);
tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:35:nn: note: when PyDict_GetItem() succeeds at:     return PyDict_GetItem(some_dict, args);
tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:35:nn: note: ob_refcnt is now refs: 0 + N where N >= 1
tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:35:nn: note: returning at:     return PyDict_GetItem(some_dict, args);
tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:35:nn: warning: returning (PyObject*)NULL without setting an exception [enabled by default]
tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:35:nn: note: when treating unknown struct PyObject * from tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:26 as non-NULL at:     return PyDict_GetItem(some_dict, args);
tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:35:nn: note: when PyDict_GetItem does not find item at:     return PyDict_GetItem(some_dict, args);
tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:35:nn: note: returning at:     return PyDict_GetItem(some_dict, args);
tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c:30:nn: note: graphical error report for function 'test' written out to 'tests/cpychecker/refcounts/PyDict_GetItem/incorrect/input.c.test-refcount-errors.html'
