tests/cpychecker/refcounts/attributes/steals-reference-to-arg/incorrect-usage/input.c: In function 'test':
tests/cpychecker/refcounts/attributes/steals-reference-to-arg/incorrect-usage/input.c:64:1: error: ob_refcnt of return value is 1 too low
tests/cpychecker/refcounts/attributes/steals-reference-to-arg/incorrect-usage/input.c:64:1: note: was expecting final ob_refcnt to be N + 1 (for some unknown N)
tests/cpychecker/refcounts/attributes/steals-reference-to-arg/incorrect-usage/input.c:64:1: note: due to object being referenced by: return value
tests/cpychecker/refcounts/attributes/steals-reference-to-arg/incorrect-usage/input.c:64:1: note: but final ob_refcnt is N + 0
tests/cpychecker/refcounts/attributes/steals-reference-to-arg/incorrect-usage/input.c:44:9: note: PyLongObject allocated at:     obj = PyLong_FromLong(42);
tests/cpychecker/refcounts/attributes/steals-reference-to-arg/incorrect-usage/input.c:44:9: note: when PyLong_FromLong() succeeds at:     obj = PyLong_FromLong(42);
tests/cpychecker/refcounts/attributes/steals-reference-to-arg/incorrect-usage/input.c:44:9: note: ob_refcnt is now refs: 1 + N where N >= 0
tests/cpychecker/refcounts/attributes/steals-reference-to-arg/incorrect-usage/input.c:45:8: note: taking False path at:     if (!obj) {
tests/cpychecker/refcounts/attributes/steals-reference-to-arg/incorrect-usage/input.c:55:8: note: reaching:     foo(obj);
tests/cpychecker/refcounts/attributes/steals-reference-to-arg/incorrect-usage/input.c:55:8: note: ob_refcnt is now refs: 0 + N where N >= 1
tests/cpychecker/refcounts/attributes/steals-reference-to-arg/incorrect-usage/input.c:64:1: note: returning
tests/cpychecker/refcounts/attributes/steals-reference-to-arg/incorrect-usage/input.c:41:1: note: graphical error report for function 'test' written out to 'tests/cpychecker/refcounts/attributes/steals-reference-to-arg/incorrect-usage/input.c.test-refcount-errors.html'
